akka {
  # Options: OFF, ERROR, WARNING, INFO, DEBUG
  loglevel = "ERROR"
  # Loggers to register at boot time (akka.event.Logging$DefaultLogger logs
  # to STDOUT)
  loggers = ["akka.event.Logging$DefaultLogger",
  "com.sunbird.lis.interfaces.middleware.core.observer.ObserverLoggingAdapter"]
 
}
DriverManager {
    MyLabHttpClient {
      resultUrl = "http://172.16.1.57:8080/EHOPE-WEB/services/submitActualTestResults.srvc"
      queryUrl = "http://localhost:8050//Machine-Integration-Web/services/getOrderOutboundInformation.srvc"
  }
}

Observer {
  endpoints {
    WebSocketServer {
      address = "127.0.0.1"
      port = 8900
    }
  }
}