package com.sunbird.lis.interfaces.middleware.util;

public enum MachineTypeEnum {

	//NRY

	//NRY
	BECHMAN_COULTER_X800("BechmanUnicile800"),
	//NRY
	SIEMENS_ADVIA_CENTAUR_XPT("AdviaCentureXP"),
	//NRY
	COBASP312("CobasP312"),
	//NRY
	SIEMENS_IMMULITE_2000_XPI("IMMULITE2000"),
	//NRY71101
	D10("D10"),
	//NRY
	SYSMEX_XP_300("SysmexXP"),
	SYSMEX_CS_2000I("SysmexCS2000"),
	//NRY
	GRIFOLS("Grifols"),
	ROCHE_COBAS_C111("CobasC111"),
	ROCHE_COBAS_C311("RocheCobasC311"),
	ROCHE_COBAS_C111_ETB("RocheCobasC111:"),
	ROCHE_COBAS_6000("Cobas6000"),
	ROCHE_COBAS_E411("CobasE411"),
	ROCHE_ELECSYS_2010("ROCHE_ELECSYS_2010"),
	//RUN
	SYSMEX_SUITE("SYSMEX_SUITE"),
	//RUN
	SYSMEX_KX_21("SysmexKX21"),
	//RUN
	HL7_24_SERVER_OVER_TCP("HL724ServerOverTcp"),
	//RUN
	DIASORIN_LIAISON_XL("DIASORIN_LIAISON_XL"),
	BECHMAN_COULTER_AU("BechmanAU"),

	BECHMAN_ACCESS_200_DXI("BECHMAN_ACCESS_200_DXI"),
	BECKMAN_UNICEL_800_DXH("BECKMAN_UNICEL_800_DXH"),
	BECHMAN_COULTER_800_DXH("BECHMAN_COULTER_800_DXH"),
	BECHMAN_COULTER_500_DXH("BECHMAN_COULTER_500_DXH"),
	BECHMAN_COULTER_AU480_DXC("BECHMAN_COULTER_AU480_DXC"),
	BIO_FLASH_200("BIO.FLASH.200"),

	INSTRUMENTATION_LABORATORY_ACL_ELITE_PRO("INSTRUMENTATION.LABORATORY.ACL.ELITE.PRO"),
	ABBOTT_ARCHITECT_CI4100("ABBOTT_ARCHITECT_CI4100"),
	ABBOTT_CELL_DYN_EMERALD_22("ABBOTT_CELL_DYN_EMERALD_22"),
	ABBOTT_CELL_DYN_RUBY("ABBOTT_CELL_DYN_RUBY"),
	ABBOTT_ALINITY_CI("ABBOTT_ALINITY_CI");

	private MachineTypeEnum(String value) {
		this.value = value;
	}

	private String value;

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}
}
